Avaliacao Class Reference
#include `entidades.h`
Public Member Functions
void setCodigoE (const Codigo &)
Codigo getCodigoE () const
void setNotaE (const Nota &)
Nota getNotaE () const
void setDescricaoE (const Descricao &)
Descricao getDescricaoE () const
Private Attributes
Codigo codigo
Nota nota
Descricao descricao
Detailed Description
Definition at line 14 of file entidades.h.
Member Function Documentation
getCodigoE()
Codigo Avaliacao::getCodigoE () const [inline]
Definition at line 33 of file entidades.h.
                                          {
    return codigo;
}
References codigo.
Referenced by TUAvaliacao::testarCenarioSucesso().
getDescricaoE()
Descricao Avaliacao::getDescricaoE () const [inline]
Definition at line 47 of file entidades.h.
                                                {
    return descricao;
}
References descricao.
Referenced by TUAvaliacao::testarCenarioSucesso().
getNotaE()
Nota Avaliacao::getNotaE () const [inline]
Definition at line 40 of file entidades.h.
                                      {
    return nota;
}
References nota.
Referenced by TUAvaliacao::testarCenarioSucesso().
setCodigoE()
void Avaliacao::setCodigoE (const Codigo & codigo) [inline]
Definition at line 30 of file entidades.h.
                                                     {
    this->codigo = codigo;
}
References codigo.
Referenced by TUAvaliacao::testarCenarioSucesso().
setDescricaoE()
void Avaliacao::setDescricaoE (const Descricao & descricao) [inline]
Definition at line 44 of file entidades.h.
                                                              {
    this->descricao = descricao;
}
References descricao.
Referenced by TUAvaliacao::testarCenarioSucesso().
setNotaE()
void Avaliacao::setNotaE (const Nota & nota) [inline]
Definition at line 37 of file entidades.h.
                                               {
    this->nota = nota;
}
References nota.
Referenced by TUAvaliacao::testarCenarioSucesso().
Member Data Documentation
codigo
Codigo Avaliacao::codigo [private]
Definition at line 16 of file entidades.h.
Referenced by getCodigoE(), and setCodigoE().
descricao
Descricao Avaliacao::descricao [private]
Definition at line 18 of file entidades.h.
Referenced by getDescricaoE(), and setDescricaoE().
nota
Nota Avaliacao::nota [private]
Definition at line 17 of file entidades.h.
Referenced by getNotaE(), and setNotaE().
The documentation for this class was generated from the following file:
entidades.h