Excursao Class Reference
#include `entidades.h`
Public Member Functions
void setCodigoE (const Codigo &)
Codigo getCodigoE () const
void setTituloE (const Titulo &)
Titulo getTituloE () const
void setNotaE (const Nota &)
Nota getNotaE () const
void setCidadeE (const Cidade &)
Cidade getCidadeE () const
void setDuracaoE (const Duracao &)
Duracao getDuracaoE () const
void setDescricaoE (const Descricao &)
Descricao getDescricaoE () const
void setEnderecoE (const Endereco &)
Endereco getEnderecoE () const
Private Attributes
Codigo codigo
Titulo titulo
Nota nota
Cidade cidade
Duracao duracao
Descricao descricao
Endereco endereco
Detailed Description
Definition at line 110 of file entidades.h.
Member Function Documentation
getCidadeE()
Cidade Excursao::getCidadeE () const [inline]
Definition at line 167 of file entidades.h.
                                         {
    return cidade;
}
References cidade.
Referenced by TUExcursao::testarCenarioSucesso().
getCodigoE()
Codigo Excursao::getCodigoE () const [inline]
Definition at line 146 of file entidades.h.
                                         {
    return codigo;
}
References codigo.
Referenced by TUExcursao::testarCenarioSucesso().
getDescricaoE()
Descricao Excursao::getDescricaoE () const [inline]
Definition at line 181 of file entidades.h.
                                               {
    return descricao;
}
References descricao.
Referenced by TUExcursao::testarCenarioSucesso().
getDuracaoE()
Duracao Excursao::getDuracaoE () const [inline]
Definition at line 174 of file entidades.h.
                                           {
    return duracao;
}
References duracao.
Referenced by TUExcursao::testarCenarioSucesso().
getEnderecoE()
Endereco Excursao::getEnderecoE () const [inline]
Definition at line 188 of file entidades.h.
                                             {
    return endereco;
}
References endereco.
Referenced by TUExcursao::testarCenarioSucesso().
getNotaE()
Nota Excursao::getNotaE () const [inline]
Definition at line 160 of file entidades.h.
                                     {
    return nota;
}
References nota.
Referenced by TUExcursao::testarCenarioSucesso().
getTituloE()
Titulo Excursao::getTituloE () const [inline]
Definition at line 153 of file entidades.h.
                                         {
    return titulo;
}
References titulo.
Referenced by TUExcursao::testarCenarioSucesso().
setCidadeE()
void Excursao::setCidadeE (const Cidade & cidade) [inline]
Definition at line 164 of file entidades.h.
                                                    {
    this->cidade = cidade;
}
References cidade.
Referenced by TUExcursao::testarCenarioSucesso().
setCodigoE()
void Excursao::setCodigoE (const Codigo & codigo) [inline]
Definition at line 143 of file entidades.h.
                                                    {
    this->codigo = codigo;
}
References codigo.
Referenced by TUExcursao::testarCenarioSucesso().
setDescricaoE()
void Excursao::setDescricaoE (const Descricao & descricao) [inline]
Definition at line 178 of file entidades.h.
                                                             {
    this->descricao = descricao;
}
References descricao.
Referenced by TUExcursao::testarCenarioSucesso().
setDuracaoE()
void Excursao::setDuracaoE (const Duracao & duracao) [inline]
Definition at line 171 of file entidades.h.
                                                       {
    this->duracao = duracao;
}
References duracao.
Referenced by TUExcursao::testarCenarioSucesso().
setEnderecoE()
void Excursao::setEnderecoE (const Endereco & endereco) [inline]
Definition at line 185 of file entidades.h.
                                                          {
    this->endereco = endereco;
}
References endereco.
Referenced by TUExcursao::testarCenarioSucesso().
setNotaE()
void Excursao::setNotaE (const Nota & nota) [inline]
Definition at line 157 of file entidades.h.
                                              {
    this->nota = nota;
}
References nota.
Referenced by TUExcursao::testarCenarioSucesso().
setTituloE()
void Excursao::setTituloE (const Titulo & titulo) [inline]
Definition at line 150 of file entidades.h.
                                                    {
    this->titulo = titulo;
}
References titulo.
Referenced by TUExcursao::testarCenarioSucesso().
Member Data Documentation
cidade
Cidade Excursao::cidade [private]
Definition at line 115 of file entidades.h.
Referenced by getCidadeE(), and setCidadeE().
codigo
Codigo Excursao::codigo [private]
Definition at line 112 of file entidades.h.
Referenced by getCodigoE(), and setCodigoE().
descricao
Descricao Excursao::descricao [private]
Definition at line 117 of file entidades.h.
Referenced by getDescricaoE(), and setDescricaoE().
duracao
Duracao Excursao::duracao [private]
Definition at line 116 of file entidades.h.
Referenced by getDuracaoE(), and setDuracaoE().
endereco
Endereco Excursao::endereco [private]
Definition at line 118 of file entidades.h.
Referenced by getEnderecoE(), and setEnderecoE().
nota
Nota Excursao::nota [private]
Definition at line 114 of file entidades.h.
Referenced by getNotaE(), and setNotaE().
titulo
Titulo Excursao::titulo [private]
Definition at line 113 of file entidades.h.
Referenced by getTituloE(), and setTituloE().
The documentation for this class was generated from the following file:
entidades.h