Data Class Reference
#include `dominio.h`
Public Member Functions
void setData (string)
const string getData ()
Private Member Functions
void validar (string)
Private Attributes
string data
Detailed Description
A Classe de Data
Definition at line 109 of file dominio.h.
Member Function Documentation
getData()
const string Data::getData () [inline]
Definition at line 120 of file dominio.h.
                                 {
    return data;
}
References data.
Referenced by TUData::testarCenarioFalha(), TUData::testarCenarioSucesso(), and TUSessao::testarCenarioSucesso().
setData()
void Data::setData (string data)
Apos a validacao da data, este e passado para o interior da classe
Definition at line 236 of file dominio.cpp.
                             {
    validar(data);
    this->data = data;
}
References data, and validar().
Referenced by TUData::testarCenarioFalha(), TUData::testarCenarioSucesso(), and TUSessao::testarCenarioSucesso().
validar()
void Data::validar (string data) [private]
Validacao da Data em que dia, mes e ano, serao representados por ANO, MES, ANO, respectivamente. Tratamento do ano
Tratamento dos Meses com 30 dias
Tratamento dos Meses com 31 dias
Tratamento do mes de Fevereiro.
Definition at line 159 of file dominio.cpp.
                             {
    std::smatch matches;
    string DIA, MES, ANO;
    regex DATA_VALIDA ("\\b(\\d{2})[- /\\.]([a-zA-Z]{3})[- /\\.](\\d{4})\\b");
    regex JAN ("[jJ][aA][nN]"); //a Codificacao dos meses generaliza
    regex FEV ("[fF][eE][vV]"); //a entrada, sendo no-sensitive.
    regex MAR ("[mM][aA][rR]");
    regex ABR ("[aA][bB][rR]");
    regex MAI ("[mM][aA][iI]");
    regex JUN ("[jJ][uU][nN]");
    regex JUL ("[jJ][uU][lL]");
    regex AGO ("[aA][gG][oO]");
    regex SET ("[sS][eE][tT]");
    regex OUT ("[oO][uU][tT]");
    regex NOV ("[nN][oO][vV]");
    regex DEZ ("[dD][eE][zZ]");
    if(regex_search(data, matches, DATA_VALIDA)){
        DIA = matches.str(1); // Aqui será guardado DIA, MES e ANO
        MES = matches.str(2); // o tratamento da data será facilitado
        ANO = matches.str(3);
        int ano = stoi(ANO);
        if (ano<2000 || ano>9999){ // Verificacao do ano.
            throw invalid_argument("Entrada invalida. O ano deve ser entre 2000 - 9999.");
        }
        if (regex_match(MES,ABR) || regex_match(MES,JUN) ||
            regex_match(MES,SET) || regex_match(MES,NOV)){
            int dia30 = stoi(DIA);
            if(dia30<1 || dia30>30)
                throw invalid_argument("Entrada invalida. Este mes possui 30 dias.");
        }
        if (regex_match(MES,JAN) || regex_match(MES,MAR) ||
            regex_match(MES,MAI) || regex_match(MES,JUL) ||
            regex_match(MES,AGO) || regex_match(MES,OUT) ||
            regex_match(MES,DEZ)){
            int dia31 = stoi(DIA);
            if(dia31<1 || dia31>31)
                throw invalid_argument("Entrada invalida. Este mes possui 31 dias.");
        }
        if (regex_match(MES, FEV)){
            int diaMaxFev = stoi(DIA);
            if(diaMaxFev>29){
                throw invalid_argument("Entrada invalida. Fevereiro nao possui mais de 29 dias");
            }else if(diaMaxFev == 29 && !(ano%4 == 0 && (ano%100 != 0 || ano%400 == 0))){
                    throw invalid_argument("Entrada invalida. Este ano nao e bissexto.");
                    }
        }
    }else{
        throw invalid_argument("Data invalida, deve ser DIA-MES-ANO, n&uacute;meros para DIA e ANO e 3 letras para o MES.");
    }
}
References data.
Referenced by setData().
Member Data Documentation
data
string Data::data [private]
Definition at line 111 of file dominio.h.
Referenced by getData(), setData(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp