Cidade Class Reference
#include `dominio.h`
Public Member Functions
void setCidade (string)
ESTA LINHA FOI ALTERADA DE char * PARA string ===========================================================.
const string getCidade ()
ESTA LINHA FOI ALTERADA DE char * PARA string ===========================================================.
Private Member Functions
void validar (string)
Ha 16 cidades validas para excursao. hong kong, bangkok, macau, singapura, londres, paris, dubai, delhi, istambul, kuala, lumpur, nova iorque, antalya, mumbai, shenzhen, phuket.
Private Attributes
string nomeCidade
Detailed Description
A Classe cidade permite o armazenamento correto das cidades disponiveis.
Definition at line 62 of file dominio.h.
Member Function Documentation
getCidade()
const string Cidade::getCidade () [inline]
ESTA LINHA FOI ALTERADA DE char * PARA string ===========================================================.
Definition at line 73 of file dominio.h.
                                     {
    return nomeCidade;
}
References nomeCidade.
Referenced by TUCidade::testarCenarioFalha(), TUCidade::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
setCidade()
void Cidade::setCidade (string nomeCidade)
ESTA LINHA FOI ALTERADA DE char * PARA string ===========================================================.
Metodo setCidade permite salvar cidade valida.
Parameters
nomeCidade
Definition at line 100 of file dominio.cpp.
                                        {
    validar(nomeCidade);
    this->nomeCidade = nomeCidade;
}
References nomeCidade, and validar().
Referenced by TUCidade::testarCenarioFalha(), TUCidade::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
validar()
void Cidade::validar (string nomeCidade) [private]
Ha 16 cidades validas para excursao. hong kong, bangkok, macau, singapura, londres, paris, dubai, delhi, istambul, kuala, lumpur, nova iorque, antalya, mumbai, shenzhen, phuket.
Parameters
nomeCidade
Definition at line 70 of file dominio.cpp.
                                     {
    // O vetor estatico e suficiente para a aplicacao
    string cidadeDisponivel[16] = {"hong kong", "bangkok", "macau", "singapura", "londres", "paris",
                                 "dubai", "delhi", "istambul", "kuala", "lumpur", "nova iorque",
                                 "antalya", "mumbai", "shenzhen", "phuket"};
    // Passar a string para minusculo garante que a funcao seja 'case no sensitive'
    lowerstr(nomeCidade);
    // A criacao de variavel auxiliar objetiva nao alterar o valor original da variavel parametro.
    string cidadeNomeAux = nomeCidade;
    // Contador de igualdade entre cidades
    int selecao = 0;
    // Mecanismo de comparacao entre parametro e vetor de cidades possiveis.
    for(int i=0; i<16; i++){
        if(cidadeNomeAux == cidadeDisponivel[i]){
            selecao = selecao+1;
        }
    }
    if (selecao != 1){
        throw invalid_argument("Cidade invalida.");
    }
}
References lowerstr(), and nomeCidade.
Referenced by setCidade().
Member Data Documentation
nomeCidade
string Cidade::nomeCidade [private]
Definition at line 64 of file dominio.h.
Referenced by getCidade(), setCidade(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp