TUExcursao Class Reference
#include `testes.h`
Public Member Functions
int run ()
Static Public Attributes
static const int SUCESSO = 0
static const int FALHA = -1
Private Member Functions
void setUp ()
void tearDown ()
void testarCenarioSucesso ()
Private Attributes
string VALOR_VALIDO1 = `123456`
string VALOR_VALIDO2 = `Excursao Safari`
string VALOR_VALIDO4 = `macau`
string VALOR_VALIDO6 = `Excurssao a pe em Macau.`
string VALOR_VALIDO7 = `Praca Civica av. L2.`
Excursao * excursao
int estado
Static Private Attributes
static const int VALOR_VALIDO3 = 1
static const int VALOR_VALIDO5 = 30
Detailed Description
Definition at line 357 of file testes.h.
Member Function Documentation
run()
int TUExcursao::run ()
Definition at line 946 of file testes.cpp.
                   {
    setUp();
    testarCenarioSucesso();
    tearDown();
    return estado;
}
References estado, setUp(), tearDown(), and testarCenarioSucesso().
Referenced by main().
setUp()
void TUExcursao::setUp () [private]
Definition at line 893 of file testes.cpp.
                      {
    excursao = new Excursao();
    estado = SUCESSO;
}
References estado, excursao, and SUCESSO.
Referenced by run().
tearDown()
void TUExcursao::tearDown () [private]
Definition at line 898 of file testes.cpp.
                         {
    delete excursao;
}
References excursao.
Referenced by run().
testarCenarioSucesso()
void TUExcursao::testarCenarioSucesso () [private]
Definition at line 902 of file testes.cpp.
                                     {
    Codigo codigo;
    codigo.setValor(VALOR_VALIDO1);
    excursao->setCodigoE(codigo);
    if(excursao->getCodigoE().getValor() != VALOR_VALIDO1)
        estado = FALHA;
    Titulo titulo;
    titulo.setTitulo(VALOR_VALIDO2);
    excursao->setTituloE(titulo);
    if(excursao->getTituloE().getTitulo() != VALOR_VALIDO2)
        estado = FALHA;
    Nota nota;
    nota.setValor(VALOR_VALIDO3);
    excursao->setNotaE(nota);
    if(excursao->getNotaE().getValor() != VALOR_VALIDO3)
        estado = FALHA;
    Cidade cidade;
    cidade.setCidade(VALOR_VALIDO4);
    excursao->setCidadeE(cidade);
    if(excursao->getCidadeE().getCidade() != VALOR_VALIDO4)
        estado = FALHA;
    Duracao duracao;
    duracao.setValor(VALOR_VALIDO5);
    excursao->setDuracaoE(duracao);
    if(excursao->getDuracaoE().getValor() != VALOR_VALIDO5)
        estado = FALHA;
    Descricao descricao;
    descricao.setDescricao(VALOR_VALIDO6);
    excursao->setDescricaoE(descricao);
    if(excursao->getDescricaoE().getDescricao() != VALOR_VALIDO6)
        estado = FALHA;
    Endereco endereco;
    endereco.setEndereco(VALOR_VALIDO7);
    excursao->setEnderecoE(endereco);
    if(excursao->getEnderecoE().getEndereco() != VALOR_VALIDO7)
        estado = FALHA;
}
References estado, excursao, FALHA, Cidade::getCidade(), Excursao::getCidadeE(), Excursao::getCodigoE(), Descricao::getDescricao(), Excursao::getDescricaoE(), Excursao::getDuracaoE(), Endereco::getEndereco(), Excursao::getEnderecoE(), Excursao::getNotaE(), Titulo::getTitulo(), Excursao::getTituloE(), Codigo::getValor(), Duracao::getValor(), Nota::getValor(), Cidade::setCidade(), Excursao::setCidadeE(), Excursao::setCodigoE(), Descricao::setDescricao(), Excursao::setDescricaoE(), Excursao::setDuracaoE(), Endereco::setEndereco(), Excursao::setEnderecoE(), Excursao::setNotaE(), Titulo::setTitulo(), Excursao::setTituloE(), Duracao::setValor(), Nota::setValor(), Codigo::setValor(), VALOR_VALIDO1, VALOR_VALIDO2, VALOR_VALIDO3, VALOR_VALIDO4, VALOR_VALIDO5, VALOR_VALIDO6, and VALOR_VALIDO7.
Referenced by run().
Member Data Documentation
estado
int TUExcursao::estado [private]
Definition at line 367 of file testes.h.
Referenced by run(), setUp(), and testarCenarioSucesso().
excursao
Excursao* TUExcursao::excursao [private]
Definition at line 366 of file testes.h.
Referenced by setUp(), tearDown(), and testarCenarioSucesso().
FALHA
const int TUExcursao::FALHA = -1 [static]
Definition at line 373 of file testes.h.
Referenced by main(), and testarCenarioSucesso().
SUCESSO
const int TUExcursao::SUCESSO = 0 [static]
Definition at line 372 of file testes.h.
Referenced by main(), and setUp().
VALOR_VALIDO1
string TUExcursao::VALOR_VALIDO1 = `123456` [private]
Definition at line 359 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO2
string TUExcursao::VALOR_VALIDO2 = `Excursao Safari` [private]
Definition at line 360 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO3
const int TUExcursao::VALOR_VALIDO3 = 1 [static], [private]
Definition at line 361 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO4
string TUExcursao::VALOR_VALIDO4 = `macau` [private]
Definition at line 362 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO5
const int TUExcursao::VALOR_VALIDO5 = 30 [static], [private]
Definition at line 363 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO6
string TUExcursao::VALOR_VALIDO6 = `Excurssao a pe em Macau.` [private]
Definition at line 364 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO7
string TUExcursao::VALOR_VALIDO7 = `Praca Civica av. L2.` [private]
Definition at line 365 of file testes.h.
Referenced by testarCenarioSucesso().
The documentation for this class was generated from the following files:
testes.h
testes.cpp