Titulo Class Reference
#include `dominio.h`
Public Member Functions
void setTitulo (string)
const string getTitulo ()
Private Member Functions
void validar (string)
Private Attributes
string titulo
Detailed Description
A Classe Titulo permite o armazenamento correto.
Definition at line 226 of file dominio.h.
Member Function Documentation
getTitulo()
const string Titulo::getTitulo () [inline]
Definition at line 237 of file dominio.h.
                                     {
    return titulo;
}
References titulo.
Referenced by TUTitulo::testarCenarioFalha(), TUTitulo::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
setTitulo()
void Titulo::setTitulo (string titulo)
Inclusao do Endereco da excursao
Parameters
endereco
Definition at line 407 of file dominio.cpp.
                                    {
    validar(titulo);
    this->titulo = titulo;
}
References titulo, and validar().
Referenced by TUTitulo::testarCenarioFalha(), TUTitulo::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
validar()
void Titulo::validar (string titulo) [private]
A validacao do endereco abrange de 0 a 20 caracteres e nao há nem espaco em branco nem ponto final em sequencia.
Parameters
descricao l
Definition at line 389 of file dominio.cpp.
                                 {
    smatch matches;
    regex TITULO_INVALIDO("([ ]{2,})|([.]{2,})|([0-9])");
    if(regex_search(titulo,matches,TITULO_INVALIDO)){ //||
       //regex_search(titulo,matches,TITULO_INVALIDO2))
        throw invalid_argument ("Endereco invalido. E permitido apenas letras e use apenas 1 espaco e ponto por vez.");
    }
    if(titulo.length()<5 || titulo.length()>20)
       throw invalid_argument("Endereco invalido. No min 5 e no max 20 caracteres.");
}
References titulo.
Referenced by setTitulo().
Member Data Documentation
titulo
string Titulo::titulo [private]
Definition at line 228 of file dominio.h.
Referenced by getTitulo(), setTitulo(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp