TUSessao Class Reference
#include `testes.h`
Public Member Functions
int run ()
Static Public Attributes
static const int SUCESSO = 0
static const int FALHA = -1
Private Member Functions
void setUp ()
void tearDown ()
void testarCenarioSucesso ()
Private Attributes
string VALOR_VALIDO1 = `123456`
string VALOR_VALIDO2 = `12 abr 2007`
string VALOR_VALIDO3 = `23:59`
string VALOR_VALIDO4 = `PortugUES`
Sessao * sessao
int estado
Detailed Description
Definition at line 339 of file testes.h.
Member Function Documentation
run()
int TUSessao::run ()
Definition at line 881 of file testes.cpp.
                 {
    setUp();
    testarCenarioSucesso();
    tearDown();
    return estado;
}
References estado, setUp(), tearDown(), and testarCenarioSucesso().
Referenced by main().
setUp()
void TUSessao::setUp () [private]
Definition at line 846 of file testes.cpp.
                    {
    sessao = new Sessao();
    estado = SUCESSO;
}
References estado, sessao, and SUCESSO.
Referenced by run().
tearDown()
void TUSessao::tearDown () [private]
Definition at line 851 of file testes.cpp.
                       {
    delete sessao;
}
References sessao.
Referenced by run().
testarCenarioSucesso()
void TUSessao::testarCenarioSucesso () [private]
Definition at line 855 of file testes.cpp.
                                   {
    Codigo codigo;
    codigo.setValor(VALOR_VALIDO1);
    sessao->setCodigoE(codigo);
    if(sessao->getCodigoE().getValor() != VALOR_VALIDO1)
        estado = FALHA;
    Data data;
    data.setData(VALOR_VALIDO2);
    sessao->setDataE(data);
    if(sessao->getDataE().getData() != VALOR_VALIDO2)
        estado = FALHA;
    Horario horario;
    horario.setHorario(VALOR_VALIDO3);
    sessao->setHorarioE(horario);
    if(sessao->getHorarioE().getHorario() != VALOR_VALIDO3)
        estado = FALHA;
    Idioma idioma;
    idioma.setIdioma(VALOR_VALIDO4);
    sessao->setIdiomaE(idioma);
    if(sessao->getIdiomaE().getIdioma() != VALOR_VALIDO4)
        estado = FALHA;
}
References estado, FALHA, Sessao::getCodigoE(), Data::getData(), Sessao::getDataE(), Horario::getHorario(), Sessao::getHorarioE(), Idioma::getIdioma(), Sessao::getIdiomaE(), Codigo::getValor(), sessao, Sessao::setCodigoE(), Data::setData(), Sessao::setDataE(), Horario::setHorario(), Sessao::setHorarioE(), Idioma::setIdioma(), Sessao::setIdiomaE(), Codigo::setValor(), VALOR_VALIDO1, VALOR_VALIDO2, VALOR_VALIDO3, and VALOR_VALIDO4.
Referenced by run().
Member Data Documentation
estado
int TUSessao::estado [private]
Definition at line 346 of file testes.h.
Referenced by run(), setUp(), and testarCenarioSucesso().
FALHA
const int TUSessao::FALHA = -1 [static]
Definition at line 352 of file testes.h.
Referenced by main(), and testarCenarioSucesso().
sessao
Sessao* TUSessao::sessao [private]
Definition at line 345 of file testes.h.
Referenced by setUp(), tearDown(), and testarCenarioSucesso().
SUCESSO
const int TUSessao::SUCESSO = 0 [static]
Definition at line 351 of file testes.h.
Referenced by main(), and setUp().
VALOR_VALIDO1
string TUSessao::VALOR_VALIDO1 = `123456` [private]
Definition at line 341 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO2
string TUSessao::VALOR_VALIDO2 = `12 abr 2007` [private]
Definition at line 342 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO3
string TUSessao::VALOR_VALIDO3 = `23:59` [private]
Definition at line 343 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO4
string TUSessao::VALOR_VALIDO4 = `PortugUES` [private]
Definition at line 344 of file testes.h.
Referenced by testarCenarioSucesso().
The documentation for this class was generated from the following files:
testes.h
testes.cpp