Descricao Class Reference
#include `dominio.h`
Public Member Functions
void setDescricao (string)
const string getDescricao ()
Private Member Functions
void validar (string)
Private Attributes
string descricao
Detailed Description
Classe Descrição
Definition at line 132 of file dominio.h.
Member Function Documentation
getDescricao()
const string Descricao::getDescricao () [inline]
Definition at line 143 of file dominio.h.
                                           {
    return descricao;
}
References descricao.
Referenced by TUDescricao::testarCenarioFalha(), TUDescricao::testarCenarioSucesso(), TUAvaliacao::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
setDescricao()
void Descricao::setDescricao (string descricao)
Inclusao da descricao da excursao
Parameters
descricao
Definition at line 267 of file dominio.cpp.
                                             {
    validar(descricao);
    this->descricao = descricao;
}
References descricao, and validar().
Referenced by TUDescricao::testarCenarioFalha(), TUDescricao::testarCenarioSucesso(), TUAvaliacao::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
validar()
void Descricao::validar (string descricao) [private]
A validacao da descricao abrange de 0 a 30 caracteres e nao ha nem espaco em branco nem ponto final em sequencia.
Parameters
descricao
Definition at line 249 of file dominio.cpp.
                                       {
    smatch matches;
    regex DESCRICAO_INVALIDA("([ ]{2,})"); //análise para cada caso separadamente.
    regex DESCRICAO_INVALIDA2("([.]{2,})");
    if(regex_search(descricao,matches,DESCRICAO_INVALIDA) ||
       regex_search(descricao,matches,DESCRICAO_INVALIDA2))
        throw invalid_argument ("Descricao invalida. use apenas 1 espaco e ponto por vez.");
    if(descricao.length()>30)
        throw invalid_argument("Entrada invalida. No max 30 caracteres.");
}
References descricao.
Referenced by setDescricao().
Member Data Documentation
descricao
string Descricao::descricao [private]
Definition at line 134 of file dominio.h.
Referenced by getDescricao(), setDescricao(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp