TUAvaliacao Class Reference
Declaração de header file das entidades.
#include `testes.h`
Public Member Functions
int run ()
Static Public Attributes
static const int SUCESSO = 0
static const int FALHA = -1
Private Member Functions
void setUp ()
void tearDown ()
void testarCenarioSucesso ()
Private Attributes
string VALOR_VALIDO1 = `123456`
string VALOR_VALIDO3 = `Excurssao a pe em Macau.`
Avaliacao * avaliacao
int estado
Static Private Attributes
static const int VALOR_VALIDO2 = 1
Detailed Description
Declaração de header file das entidades.
Definition at line 307 of file testes.h.
Member Function Documentation
run()
int TUAvaliacao::run ()
Definition at line 795 of file testes.cpp.
                    {
    setUp();
    testarCenarioSucesso();
    tearDown();
    return estado;
}
References estado, setUp(), tearDown(), and testarCenarioSucesso().
Referenced by main().
setUp()
void TUAvaliacao::setUp () [private]
Definition at line 766 of file testes.cpp.
                       {
    avaliacao = new Avaliacao();
    estado = SUCESSO;
}
References avaliacao, estado, and SUCESSO.
Referenced by run().
tearDown()
void TUAvaliacao::tearDown () [private]
Definition at line 771 of file testes.cpp.
                          {
    delete avaliacao;
}
References avaliacao.
Referenced by run().
testarCenarioSucesso()
void TUAvaliacao::testarCenarioSucesso () [private]
Definition at line 775 of file testes.cpp.
                                      {
    Codigo codigo;
    codigo.setValor(VALOR_VALIDO1);
    avaliacao->setCodigoE(codigo);
    if(avaliacao->getCodigoE().getValor() != VALOR_VALIDO1)
        estado = FALHA;
    Nota nota;
    nota.setValor(VALOR_VALIDO2);
    avaliacao->setNotaE(nota);
    if(avaliacao->getNotaE().getValor() != VALOR_VALIDO2)
        estado = FALHA;
    Descricao descricao;
    descricao.setDescricao(VALOR_VALIDO3);
    avaliacao->setDescricaoE(descricao);
    if(avaliacao->getDescricaoE().getDescricao() != VALOR_VALIDO3)
        estado = FALHA;
}
References avaliacao, estado, FALHA, Avaliacao::getCodigoE(), Descricao::getDescricao(), Avaliacao::getDescricaoE(), Avaliacao::getNotaE(), Codigo::getValor(), Nota::getValor(), Avaliacao::setCodigoE(), Descricao::setDescricao(), Avaliacao::setDescricaoE(), Avaliacao::setNotaE(), Nota::setValor(), Codigo::setValor(), VALOR_VALIDO1, VALOR_VALIDO2, and VALOR_VALIDO3.
Referenced by run().
Member Data Documentation
avaliacao
Avaliacao* TUAvaliacao::avaliacao [private]
Definition at line 312 of file testes.h.
Referenced by setUp(), tearDown(), and testarCenarioSucesso().
estado
int TUAvaliacao::estado [private]
Definition at line 313 of file testes.h.
Referenced by run(), setUp(), and testarCenarioSucesso().
FALHA
const int TUAvaliacao::FALHA = -1 [static]
Definition at line 319 of file testes.h.
Referenced by main(), and testarCenarioSucesso().
SUCESSO
const int TUAvaliacao::SUCESSO = 0 [static]
Definition at line 318 of file testes.h.
Referenced by main(), and setUp().
VALOR_VALIDO1
string TUAvaliacao::VALOR_VALIDO1 = `123456` [private]
Definition at line 309 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO2
const int TUAvaliacao::VALOR_VALIDO2 = 1 [static], [private]
Definition at line 310 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO3
string TUAvaliacao::VALOR_VALIDO3 = `Excurssao a pe em Macau.` [private]
Definition at line 311 of file testes.h.
Referenced by testarCenarioSucesso().
The documentation for this class was generated from the following files:
testes.h
testes.cpp