Codigo Class Reference
#include `dominio.h`
Public Member Functions
void setValor (string)
const string getValor ()
Private Member Functions
void validar (string)
Validacao de codigo de excursao.
Private Attributes
string valor
Detailed Description
A Classe Codigo determina o código para escurssão. Os 6 primeiros digitos são de código e o 7º é digito verificador. O algorítimo de verificação será `Módulo 11`, também usado para determinar numero de identidade (RG) SSP-SP.
Definition at line 87 of file dominio.h.
Member Function Documentation
getValor()
const string Codigo::getValor () [inline]
Definition at line 98 of file dominio.h.
                                    {
    return valor;
}
References valor.
Referenced by TUCodigo::testarCenarioFalha(), TUCodigo::testarCenarioSucesso(), TUAvaliacao::testarCenarioSucesso(), TUSessao::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
setValor()
void Codigo::setValor (string valor)
Apos a validacao do codigo, este e passado para o interior da classe
Definition at line 146 of file dominio.cpp.
                                 {
    validar(valor);
    this->valor = valor;
}
References validar(), and valor.
Referenced by TUCodigo::testarCenarioFalha(), TUCodigo::testarCenarioSucesso(), TUAvaliacao::testarCenarioSucesso(), TUSessao::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
validar()
void Codigo::validar (string valor) [private]
Validacao de codigo de excursao.
Codigo deve ser composto por 6 digitos numericos, salvo codigo '000000'. O setimo caracter e o dgito verificador. algoritmo de verificacao => Ttulo eleitoral <A HREF = `http://ghiorzi.org/DVnew.htm`
Parameters
string valor
Algoritmo de Dgito de verificacao (Ttulo Eleitoral)
Definition at line 112 of file dominio.cpp.
                                {
    int numerador = stoi(valor); // Conversão de string para int;
    int somatorio = 0;
    int resto = 0;
    int i=0; // Índice Multiplicativo.
    regex CODIGO_VALIDO ("[0-9]{6}"); // código aceitável
    regex CODIGO_INVALIDO ("[0]{1,6}"); // código inválido.
    int DV=0; // Digito Verificador
    if (regex_match(valor, CODIGO_INVALIDO) || !regex_match(valor, CODIGO_VALIDO))
        throw invalid_argument("Codigo invalido. O codigo deve conter 6 algarismos diferente de 000000.");
    while(numerador>0){ // Neste laço cada algarismo é multiplicado por
        resto = (numerador%10)*(9-i); // uma constante diferente, conforme o algoritmo.
        somatorio = somatorio+resto;
        numerador = numerador/10;
        i++;
    }
    DV = somatorio % 11; //O resto esta em INT
    if(DV == 10) // Condicao para %11 (div. por 11) = 10
        DV=0;
    valor = valor+to_string(DV);
}
References valor.
Referenced by setValor().
Member Data Documentation
valor
string Codigo::valor [private]
Definition at line 89 of file dominio.h.
Referenced by getValor(), setValor(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp