Nota Class Reference
#include `dominio.h`
Public Member Functions
void setValor (int valor)
Metodo setValor permite salvar numeros validos.
int getValor () const
Private Member Functions
void validar (int)
Validacao de nota.
Private Attributes
int valor
Detailed Description
Classe Nota permite o armazenamento da avaliação dada pelo usuário para aquela excursão
Definition at line 41 of file dominio.h.
Member Function Documentation
getValor()
int Nota::getValor () const [inline]
Definition at line 50 of file dominio.h.
                               {
    return valor;
}
References valor.
Referenced by TUNota::testarCenarioFalha(), TUNota::testarCenarioSucesso(), TUAvaliacao::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
setValor()
void Nota::setValor (int valor)
Metodo setValor permite salvar numeros validos.
Parameters
valor
Definition at line 60 of file dominio.cpp.
                            {
    Nota::validar(valor);
    this->valor = valor;
}
References validar(), and valor.
Referenced by TUNota::testarCenarioFalha(), TUNota::testarCenarioSucesso(), TUAvaliacao::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
validar()
void Nota::validar (int valor) [private]
Validacao de nota.
Parameters
valor
Definition at line 52 of file dominio.cpp.
                           {
    if (valor != 0 && valor != 1 && valor != 2 && valor != 3 && valor != 4 && valor != 5)
        throw invalid_argument("Nota invalida.");
}
References valor.
Referenced by setValor().
Member Data Documentation
valor
int Nota::valor [private]
Definition at line 43 of file dominio.h.
Referenced by getValor(), setValor(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp