Usuario Class Reference
#include `entidades.h`
Public Member Functions
void setNomeE (const Nome &)
Nome getNomeE () const
void setEmailE (const Email &)
Email getEmailE () const
void setSenhaE (const Senha &)
Senha getSenhaE () const
Private Attributes
Nome nome
Email email
Senha senha
Detailed Description
Definition at line 195 of file entidades.h.
Member Function Documentation
getEmailE()
Email Usuario::getEmailE () const [inline]
Definition at line 221 of file entidades.h.
                                      {
    return email;
}
References email.
Referenced by TUUsuario::testarCenarioSucesso().
getNomeE()
Nome Usuario::getNomeE () const [inline]
Definition at line 214 of file entidades.h.
                                    {
    return nome;
}
References nome.
Referenced by TUUsuario::testarCenarioSucesso().
getSenhaE()
Senha Usuario::getSenhaE () const [inline]
Definition at line 228 of file entidades.h.
                                      {
    return senha;
}
References senha.
Referenced by TUUsuario::testarCenarioSucesso().
setEmailE()
void Usuario::setEmailE (const Email & email) [inline]
Definition at line 218 of file entidades.h.
                                                {
    this->email = email;
}
References email.
Referenced by TUUsuario::testarCenarioSucesso().
setNomeE()
void Usuario::setNomeE (const Nome & nome) [inline]
Definition at line 211 of file entidades.h.
                                             {
    this->nome = nome;
}
References nome.
Referenced by TUUsuario::testarCenarioSucesso().
setSenhaE()
void Usuario::setSenhaE (const Senha & senha) [inline]
Definition at line 225 of file entidades.h.
                                                {
    this->senha = senha;
}
References senha.
Referenced by TUUsuario::testarCenarioSucesso().
Member Data Documentation
email
Email Usuario::email [private]
Definition at line 198 of file entidades.h.
Referenced by getEmailE(), and setEmailE().
nome
Nome Usuario::nome [private]
Definition at line 197 of file entidades.h.
Referenced by getNomeE(), and setNomeE().
senha
Senha Usuario::senha [private]
Definition at line 199 of file entidades.h.
Referenced by getSenhaE(), and setSenhaE().
The documentation for this class was generated from the following file:
entidades.h