Horario Class Reference
#include `dominio.h`
Public Member Functions
void setHorario (string)
const string getHorario ()
Private Member Functions
void validar (string)
Private Attributes
string horario
Detailed Description
Classe Horario
Definition at line 179 of file dominio.h.
Member Function Documentation
getHorario()
const string Horario::getHorario () [inline]
Definition at line 190 of file dominio.h.
                                       {
    return horario;
}
References horario.
Referenced by TUHorario::testarCenarioFalha(), TUHorario::testarCenarioSucesso(), and TUSessao::testarCenarioSucesso().
setHorario()
void Horario::setHorario (string horario)
Inclusao do Horario da excursao
Parameters
endereco
Definition at line 333 of file dominio.cpp.
                                       {
    validar(horario);
    this->horario = horario;
}
References horario, and validar().
Referenced by TUHorario::testarCenarioFalha(), TUHorario::testarCenarioSucesso(), and TUSessao::testarCenarioSucesso().
validar()
void Horario::validar (string horario) [private]
A validacao do Horario abrange de 00-23 Horas e 00-59 minutos.
Parameters
horario
Definition at line 311 of file dominio.cpp.
                                   {
    smatch matches;
    string HH, MM;
    int hora, minuto;
    regex HORA_VALIDA("([0-2][0-9])[:]([0-5][0-9])");
    if(regex_search(horario,matches,HORA_VALIDA)){
        HH = matches.str(1);
        hora = stoi(HH);
        MM = matches.str(2);
        minuto = stoi(MM);
        if(hora<0 || hora>23 || minuto<0 || minuto>59)
            throw invalid_argument("Horario invalido. Formato valido: 00:00 ate 23:59.");
    }else{throw invalid_argument("Formato de horario invalido.");}
}
References horario.
Referenced by setHorario().
Member Data Documentation
horario
string Horario::horario [private]
Definition at line 181 of file dominio.h.
Referenced by getHorario(), setHorario(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp