Endereco Class Reference
#include `dominio.h`
Public Member Functions
void setEndereco (string)
const string getEndereco ()
Private Member Functions
void validar (string)
Private Attributes
string endereco
Detailed Description
Classe Endereço
Definition at line 155 of file dominio.h.
Member Function Documentation
getEndereco()
const string Endereco::getEndereco () [inline]
Definition at line 166 of file dominio.h.
                                         {
    return endereco;
}
References endereco.
Referenced by TUEndereco::testarCenarioFalha(), TUEndereco::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
setEndereco()
void Endereco::setEndereco (string endereco)
Inclusao do Endereco da excursao
Parameters
endereco
Definition at line 299 of file dominio.cpp.
                                          {
    validar(endereco);
    this->endereco = endereco;
}
References endereco, and validar().
Referenced by TUEndereco::testarCenarioFalha(), TUEndereco::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
validar()
void Endereco::validar (string endereco) [private]
A validacao do endereco abrange de 0 a 20 caracteres e nao ha nem espaco em branco nem ponto final em sequencia.
Parameters
descricao
Definition at line 281 of file dominio.cpp.
                                     {
    smatch matches;
    regex ENDERECO_INVALIDO("([ ]{2,})"); //análise para cada caso separadamente.
    regex ENDERECO_INVALIDO2("([.]{2,})");
    if(regex_search(endereco,matches,ENDERECO_INVALIDO) ||
       regex_search(endereco,matches,ENDERECO_INVALIDO2))
        throw invalid_argument ("Endereco invalido. use apenas 1 espaco e ponto por vez.");
    if(endereco.length()>20)
        throw invalid_argument("Endereco invalido. No max 20 caracteres.");
}
References endereco.
Referenced by setEndereco().
Member Data Documentation
endereco
string Endereco::endereco [private]
Definition at line 157 of file dominio.h.
Referenced by getEndereco(), setEndereco(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp