Nome Class Reference
#include `dominio.h`
Public Member Functions
void setNome (string)
const string getNome ()
Private Member Functions
void validar (string)
Private Attributes
string nome
Detailed Description
Classe Nome permite o armazenamento
Definition at line 294 of file dominio.h.
Member Function Documentation
getNome()
const string Nome::getNome () [inline]
Definition at line 305 of file dominio.h.
                                 {
    return nome;
}
References nome.
Referenced by TUNome::testarCenarioFalha(), TUNome::testarCenarioSucesso(), and TUUsuario::testarCenarioSucesso().
setNome()
void Nome::setNome (string nome)
Inclusao do Endereco da excursao
Parameters
nome
Definition at line 591 of file dominio.cpp.
                             {
    validar(nome);
    this->nome = nome;
}
References nome, and validar().
Referenced by TUNome::testarCenarioFalha(), TUNome::testarCenarioSucesso(), and TUUsuario::testarCenarioSucesso().
validar()
void Nome::validar (string nome) [private]
A validacao de nome
Parameters
nome
1 verificacao de nome: caracteres invalidos, comprimento de nome e formato.
2 verificacao de nome: Ocorrência nome iniciando minusculo
3 verificacao de nome: Ocorrências com ponto e espaco
Definition at line 554 of file dominio.cpp.
                             {
    smatch matches;
    stringstream ss_nome(nome);
    string intermediate;
    //regex NOME_VALIDO("[a-zA-Z \\.]{5,20}");
    regex CAR_INVALIDO("[^a-zA-Z \\.]");
    //
    regex MINUSCULO_VALIDO_MEIO("[\\. ][a-z]");
    regex MINUSCULO_VALIDO_INICIO("^[A-Z]");
    //
    regex PONTO_ESPACO_INVALIDO("([\\.][A-Za-z])|([\\.][\\.])|([ ][ ])|([ ][a-z\\.])");
    if(nome.length() < 5 || nome.length() > 20 || regex_search(nome,matches,CAR_INVALIDO))
        throw invalid_argument ("Erro: NOME_INVALIDO");
    if(regex_search(nome,matches,MINUSCULO_VALIDO_MEIO) || !regex_search(nome,matches,MINUSCULO_VALIDO_INICIO))
        throw invalid_argument ("Erro: not MINUSCULO_VALIDO");
    if(regex_search(nome,matches,PONTO_ESPACO_INVALIDO))
        throw invalid_argument ("Erro: PONTO_ESPACO_INVALIDO");
}
References nome.
Referenced by setNome().
Member Data Documentation
nome
string Nome::nome [private]
Definition at line 296 of file dominio.h.
Referenced by getNome(), setNome(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp