Senha Class Reference
#include `dominio.h`
Public Member Functions
void setSenha (string)
const string getSenha ()
Private Member Functions
void validar (string)
Private Attributes
string senha
Detailed Description
A Classe Senha permite o armazenamento correto.
Definition at line 250 of file dominio.h.
Member Function Documentation
getSenha()
const string Senha::getSenha () [inline]
Definition at line 261 of file dominio.h.
                                   {
    return senha;
}
References senha.
Referenced by TUSenha::testarCenarioFalha(), TUSenha::testarCenarioSucesso(), and TUUsuario::testarCenarioSucesso().
setSenha()
void Senha::setSenha (string segredo)
Inclusao do Endereco da excursao
Parameters
endereco
Definition at line 481 of file dominio.cpp.
                                  {
    validar(segredo);
    this->senha = segredo;
}
References senha, and validar().
Referenced by TUSenha::testarCenarioFalha(), TUSenha::testarCenarioSucesso(), and TUUsuario::testarCenarioSucesso().
validar()
void Senha::validar (string segredo) [private]
A validacao da senha abrange 6 caracteres Nao é permitido caracter repetido e deve conter, no minimo, 1 letra Mais., 1 letra min. e 1 num.
Parameters
segredo
1 verificacao de senha: caracteres invalidos e comprimento de senha.
Tratamento de Senha para verificacoes 2 e 3
2 verificacao de senha: Vedada ocorrencia de 'char' repetido em sequencia.
3 verificacao de senha: pelo menos 1 ocorrencia de 'char': minusc., maiusc., numero.
Definition at line 424 of file dominio.cpp.
                                 {
    smatch matches;
    int charMin = 0, charMai = 0, charNum = 0;
    char caracter;
    string caracterStr;
    regex CAR_MIN("[a-z]");
    regex CAR_MAI("[A-Z]");
    regex CAR_NUM("[0-9]");
    regex SENHA_INVALIDA("[ ]|[\\.]|[!@#$%&¨&*)\(+=£¢¬§]");
    if (segredo.length()<6 || segredo.length()>6 || regex_search(segredo,matches,SENHA_INVALIDA))
        throw invalid_argument ("Senha invalida. So sao permitido 6 digitos de aA-zZ 0-9.");
    for (int i=0; i<segredo.length(); i++){
        caracter = segredo[i];
        caracterStr = segredo[i];
        if(regex_match(caracterStr,CAR_MIN)){
           charMin++;
        }else{ if(regex_match(caracterStr,CAR_MAI)){
                 charMai++;
                }else{ if(regex_match(caracterStr,CAR_NUM)){
                         charNum++;
                        }
                }
        }
        if(i != (segredo.length()-1)){
            if(caracter == segredo[i+1])
            throw invalid_argument("Senha invalida. Nao e permito caracteres repetidos em sequencia.");
        }
    }
    if(charMin == 0 || charMai == 0 || charNum == 0)
            throw invalid_argument("Senha invalida. Deve conter pelo menos 1 caracter minusculo, 1 maiusculo e 1 numero");
}
Referenced by setSenha().
Member Data Documentation
senha
string Senha::senha [private]
Definition at line 252 of file dominio.h.
Referenced by getSenha(), and setSenha().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp