Sessao Class Reference
#include `entidades.h`
Public Member Functions
void setCodigoE (const Codigo &)
Codigo getCodigoE () const
void setDataE (const Data &)
Data getDataE () const
void setHorarioE (const Horario &)
Horario getHorarioE () const
void setIdiomaE (const Idioma &)
Idioma getIdiomaE () const
Private Attributes
Codigo codigo
Data data
Horario horario
Idioma idioma
Detailed Description
Definition at line 56 of file entidades.h.
Member Function Documentation
getCodigoE()
Codigo Sessao::getCodigoE () const [inline]
Definition at line 79 of file entidades.h.
                                       {
    return codigo;
}
References codigo.
Referenced by TUSessao::testarCenarioSucesso().
getDataE()
Data Sessao::getDataE () const [inline]
Definition at line 86 of file entidades.h.
                                   {
    return data;
}
References data.
Referenced by TUSessao::testarCenarioSucesso().
getHorarioE()
Horario Sessao::getHorarioE () const [inline]
Definition at line 93 of file entidades.h.
                                         {
    return horario;
}
References horario.
Referenced by TUSessao::testarCenarioSucesso().
getIdiomaE()
Idioma Sessao::getIdiomaE () const [inline]
Definition at line 100 of file entidades.h.
                                       {
    return idioma;
}
References idioma.
Referenced by TUSessao::testarCenarioSucesso().
setCodigoE()
void Sessao::setCodigoE (const Codigo & codigo) [inline]
Definition at line 76 of file entidades.h.
                                                  {
    this->codigo = codigo;
}
References codigo.
Referenced by TUSessao::testarCenarioSucesso().
setDataE()
void Sessao::setDataE (const Data & data) [inline]
Definition at line 83 of file entidades.h.
                                            {
    this->data = data;
}
References data.
Referenced by TUSessao::testarCenarioSucesso().
setHorarioE()
void Sessao::setHorarioE (const Horario & horario) [inline]
Definition at line 90 of file entidades.h.
                                                     {
    this->horario = horario;
}
References horario.
Referenced by TUSessao::testarCenarioSucesso().
setIdiomaE()
void Sessao::setIdiomaE (const Idioma & idioma) [inline]
Definition at line 97 of file entidades.h.
                                                  {
    this->idioma = idioma;
}
References idioma.
Referenced by TUSessao::testarCenarioSucesso().
Member Data Documentation
codigo
Codigo Sessao::codigo [private]
Definition at line 58 of file entidades.h.
Referenced by getCodigoE(), and setCodigoE().
data
Data Sessao::data [private]
Definition at line 59 of file entidades.h.
Referenced by getDataE(), and setDataE().
horario
Horario Sessao::horario [private]
Definition at line 60 of file entidades.h.
Referenced by getHorarioE(), and setHorarioE().
idioma
Idioma Sessao::idioma [private]
Definition at line 61 of file entidades.h.
Referenced by getIdiomaE(), and setIdiomaE().
The documentation for this class was generated from the following file:
entidades.h