Duracao Class Reference
#include `dominio.h`
Public Member Functions
void setValor (int valor)
Metodo setValor permite salvar numeros validos.
int getValor () const
Private Member Functions
void validar (int)
Duracao do passeio pode ser de 30, 60, 90, 120 ou 180 minutos. O instrutor pode oferecer seu passeio dentre estas opcoes de duracao. A funcao abaixo busca validar o valor de entrada.
Private Attributes
int valor
Detailed Description
Classe duração
O VALOR a ser armazenado sera antes validado em VALIDAR. O valor deve passar por SETVALOR antes de ser armazenado.
Definition at line 17 of file dominio.h.
Member Function Documentation
getValor()
int Duracao::getValor () const [inline]
O método GETVALOR é posto como inline para evitar custo computacional, visto que é apenas retorno de uma informação.
Definition at line 30 of file dominio.h.
                                  {
    return valor;
}
References valor.
Referenced by TUDuracao::testarCenarioFalha(), TUDuracao::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
setValor()
void Duracao::setValor (int valor)
Metodo setValor permite salvar numeros validos.
Parameters
valor
Definition at line 43 of file dominio.cpp.
                               {
    Duracao::validar(valor);
    this->valor = valor;
}
References validar(), and valor.
Referenced by TUDuracao::testarCenarioFalha(), TUDuracao::testarCenarioSucesso(), and TUExcursao::testarCenarioSucesso().
validar()
void Duracao::validar (int valor) [private]
Duracao do passeio pode ser de 30, 60, 90, 120 ou 180 minutos. O instrutor pode oferecer seu passeio dentre estas opcoes de duracao. A funcao abaixo busca validar o valor de entrada.
Parameters
valor
Definition at line 33 of file dominio.cpp.
                              {
    if (valor != 30 && valor != 60 && valor != 90 && valor != 120 && valor != 180)
        throw invalid_argument("Duracao invalida.");
}
References valor.
Referenced by setValor().
Member Data Documentation
valor
int Duracao::valor [private]
Definition at line 19 of file dominio.h.
Referenced by getValor(), setValor(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp