Email Class Reference
#include `dominio.h`
Public Member Functions
void setEmail (string)
const string getEmail ()
Private Member Functions
void validar (string)
Private Attributes
string email
Detailed Description
A Classe Email permite o armazenamento correto.
Definition at line 272 of file dominio.h.
Member Function Documentation
getEmail()
const string Email::getEmail () [inline]
Definition at line 283 of file dominio.h.
                                   {
    return email;
}
References email.
Referenced by TUEmail::testarCenarioFalha(), TUEmail::testarCenarioSucesso(), and TUUsuario::testarCenarioSucesso().
setEmail()
void Email::setEmail (string email)
Inclusao do Endereco da excursao
Parameters
endereco
Definition at line 539 of file dominio.cpp.
                                {
    validar(email);
    this->email = email;
}
References email, and validar().
Referenced by TUEmail::testarCenarioFalha(), TUEmail::testarCenarioSucesso(), and TUUsuario::testarCenarioSucesso().
validar()
void Email::validar (string email) [private]
A validacao da email abrange parte-local@dominio
Parameters
email
1 verificacao de email: caracteres invalidos, comprimento de email e formato.
2 verificacao de email: Ocorrência de ponto
3 verificacao de email: Pontos duplos
Definition at line 496 of file dominio.cpp.
                               {
    smatch matches;
    int i = 0;
    stringstream full_email(email);
    string intermediate;
    regex EMAIL_VALIDO("[a-zA-Z0-9!#\\$%&'*\\+\\-\\/=^_`{|}~\\.]{1,64}[@][a-zA-Z0-9\\.\\-]{1,253}");
    if(!regex_search(email,matches,EMAIL_VALIDO))
        throw invalid_argument ("Email invalido 1");
    while(getline(full_email, intermediate, '@')){
        if(i == 0 && (intermediate.front() == '.' || intermediate.back() == '.')){
            throw invalid_argument ("Email invalido 2A");
        }
        if(i == 1 && intermediate.front() == '.'){
            throw invalid_argument ("Email invalido 2B");
        }
        i++;
    }
    if(email.find("..") != string::npos){
        throw invalid_argument ("Email invalido 3");
    }
}
References email.
Referenced by setEmail().
Member Data Documentation
email
string Email::email [private]
Definition at line 274 of file dominio.h.
Referenced by getEmail(), setEmail(), and validar().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp