TUUsuario Class Reference
#include `testes.h`
Public Member Functions
int run ()
Static Public Attributes
static const int SUCESSO = 0
static const int FALHA = -1
Private Member Functions
void setUp ()
void tearDown ()
void testarCenarioSucesso ()
Private Attributes
string VALOR_VALIDO1 = `Iago C.`
string VALOR_VALIDO2 = `iago.cossentino@gmail.com`
string VALOR_VALIDO3 = `5EnH4a`
Usuario * usuario
int estado
Detailed Description
Definition at line 323 of file testes.h.
Member Function Documentation
run()
int TUUsuario::run ()
Definition at line 835 of file testes.cpp.
                  {
    setUp();
    testarCenarioSucesso();
    tearDown();
    return estado;
}
References estado, setUp(), tearDown(), and testarCenarioSucesso().
Referenced by main().
setUp()
void TUUsuario::setUp () [private]
Definition at line 806 of file testes.cpp.
                     {
    usuario = new Usuario();
    estado = SUCESSO;
}
References estado, SUCESSO, and usuario.
Referenced by run().
tearDown()
void TUUsuario::tearDown () [private]
Definition at line 811 of file testes.cpp.
                        {
    delete usuario;
}
References usuario.
Referenced by run().
testarCenarioSucesso()
void TUUsuario::testarCenarioSucesso () [private]
Definition at line 815 of file testes.cpp.
                                    {
    Nome nome;
    nome.setNome(VALOR_VALIDO1);
    usuario->setNomeE(nome);
    if(usuario->getNomeE().getNome() != VALOR_VALIDO1)
        estado = FALHA;
    Email email;
    email.setEmail(VALOR_VALIDO2);
    usuario->setEmailE(email);
    if(usuario->getEmailE().getEmail() != VALOR_VALIDO2)
        estado = FALHA;
    Senha senha;
    senha.setSenha(VALOR_VALIDO3);
    usuario->setSenhaE(senha);
    if(usuario->getSenhaE().getSenha() != VALOR_VALIDO3)
        estado = FALHA;
}
References estado, FALHA, Email::getEmail(), Usuario::getEmailE(), Nome::getNome(), Usuario::getNomeE(), Senha::getSenha(), Usuario::getSenhaE(), Email::setEmail(), Usuario::setEmailE(), Nome::setNome(), Usuario::setNomeE(), Senha::setSenha(), Usuario::setSenhaE(), usuario, VALOR_VALIDO1, VALOR_VALIDO2, and VALOR_VALIDO3.
Referenced by run().
Member Data Documentation
estado
int TUUsuario::estado [private]
Definition at line 329 of file testes.h.
Referenced by run(), setUp(), and testarCenarioSucesso().
FALHA
const int TUUsuario::FALHA = -1 [static]
Definition at line 335 of file testes.h.
Referenced by main(), and testarCenarioSucesso().
SUCESSO
const int TUUsuario::SUCESSO = 0 [static]
Definition at line 334 of file testes.h.
Referenced by main(), and setUp().
usuario
Usuario* TUUsuario::usuario [private]
Definition at line 328 of file testes.h.
Referenced by setUp(), tearDown(), and testarCenarioSucesso().
VALOR_VALIDO1
string TUUsuario::VALOR_VALIDO1 = `Iago C.` [private]
Definition at line 325 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO2
string TUUsuario::VALOR_VALIDO2 = `iago.cossentino@gmail.com` [private]
Definition at line 326 of file testes.h.
Referenced by testarCenarioSucesso().
VALOR_VALIDO3
string TUUsuario::VALOR_VALIDO3 = `5EnH4a` [private]
Definition at line 327 of file testes.h.
Referenced by testarCenarioSucesso().
The documentation for this class was generated from the following files:
testes.h
testes.cpp