Idioma Class Reference
#include `dominio.h`
Public Member Functions
void setIdioma (string)
ESTA LINHA FOI DE char* PARA string.
const string getIdioma ()
ESTA LINHA FOI DE char* PARA string.
Private Member Functions
void validar (string)
Private Attributes
string idioma
Detailed Description
A Classe Idioma permite o armazenamento correto dos idiomas disponiveis.
Definition at line 202 of file dominio.h.
Member Function Documentation
getIdioma()
const string Idioma::getIdioma () [inline]
ESTA LINHA FOI DE char* PARA string.
Definition at line 213 of file dominio.h.
                                     {
    return idioma;
}
References idioma.
Referenced by TUIdioma::testarCenarioFalha(), TUIdioma::testarCenarioSucesso(), and TUSessao::testarCenarioSucesso().
setIdioma()
void Idioma::setIdioma (string linguagem)
ESTA LINHA FOI DE char* PARA string.
Antes de incluir o idioma deve-se verificar se esta na lista de idiomas disponiveis.
Parameters
idioma
ESTA LINHA FOI DE char* PARA string
Definition at line 375 of file dominio.cpp.
                                       {
    validar(linguagem);
    this->idioma = linguagem;
}
References idioma, and validar().
Referenced by TUIdioma::testarCenarioFalha(), TUIdioma::testarCenarioSucesso(), and TUSessao::testarCenarioSucesso().
validar()
void Idioma::validar (string linguagem) [private]
A funcao recebe um vetor de char pois e mais pratico de se manipular. Apos transformar a string para padrao minusculo, pode ser feita comparacao.
Parameters
idioma
ESTA LINHA FOI DE char* PARA string
O vetor de string estatico e sulficiente para a aplicacao, pois os Idiomas sao constante
Definition at line 347 of file dominio.cpp.
                                    {
    string idiomaDisponivel[10] = {"ingles", "chines mandarim", "hindi", "espanhol", "frances", "arabe",
                                   "bengali", "russo", "portugues", "indonesio"};
    lowerstr(linguagem);
    //strlwr(linguagem); // Manipula a string para min&uacute;sculo e salva na mesma vari&aacute;vel
    string idiomaAux = linguagem;
    int selecao = 0; // Contador de igualdade entre cidades
    for(int i=0; i<10; i++){
        if(idiomaAux == idiomaDisponivel[i]){
            selecao = selecao+1;
        }
    }
    if (selecao != 1){
        throw invalid_argument("Idioma invalido. Suas opcoes sao: ingles, chines mandarim, hindi, espanhol, frances, arabe, bengali, russo, portugues, indonesio");
    }
}
References lowerstr().
Referenced by setIdioma().
Member Data Documentation
idioma
string Idioma::idioma [private]
Definition at line 204 of file dominio.h.
Referenced by getIdioma(), and setIdioma().
The documentation for this class was generated from the following files:
dominio.h
dominio.cpp